### ISSUE TITLE
Fb group hack, SMS spoof are not working

### ISSUE THREAD

**Issue by hackersteve41** [Gameye98/santet-online#2]
Fbghack returns with error "There was a problem adding group administrator".
SMS spoof gives success message but it doesn't send any spoof message

**Comment by rnayabed** [comment]
Fb Hack wont work probably because facebook changed its algorithm...
For SMS spoof, please have a look at Issue #1

**Comment by hackersteve41** [comment]
Oh tq bro I will go through it

**Comment by hackersteve41** [comment]
Your products are amazing keep it up bro

**Comment by rnayabed** [comment]
Actually I am not the maker of this program. I am just a contributer. I just added an exception handler and form validation features.... Check my profile to know more ;)

**Comment by masyroni** [comment]
Im not the maker of this program
