### ISSUE TITLE
cannot open valid print

### ISSUE THREAD

**Issue by herpgamers** [Gameye98/santet-online#4]
invalid print """

**Comment by dCHACKZz** [comment]
Same issue

**Comment by SteveDaHacker** [comment]
Guys just use not :
$python santet.py

Use this :
$python2 santet.py

**Comment by worstone629** [comment]
it is not working even after using
$python2 santet.py
it is showing some thing like this

tr
![Screenshot_2019-10-26-06-37-34](https://user-images.githubusercontent.com/48437728/67611875-26002700-f7bb-11e9-806d-56e0ea43f582.png)
aceback (most recent call last):
  File "santet.py", line 7, in <module>
    from core.onlen import *
  File "/data/data/com.termux/files/home/santet-online/core/onlen.py", line 9, in <module>
    import requests
ImportError: No module named requests

**Comment by EulerIExponent** [comment]
> it is not working even after using
> $python2 santet.py
> it is showing some thing like this
> 
> tr
> ![Screenshot_2019-10-26-06-37-34](https://user-images.githubusercontent.com/48437728/67611875-26002700-f7bb-11e9-806d-56e0ea43f582.png)
> aceback (most recent call last):
> File "santet.py", line 7, in
> from core.onlen import *
> File "/data/data/com.termux/files/home/santet-online/core/onlen.py", line 9, in
> import requests
> ImportError: No module named requests

Open new tab and type this command : pip2 install requests

**Comment by Gameye98** [comment]
shambhunathmaji always make sure to follow the installation guide on README.md
you need to install the require module like telethon and requests
